
package tns.activatesubcriber;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WSActivatedSubcriber", targetNamespace = "http://activateSubcriber.tns")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSActivatedSubcriber {


    /**
     * 
     * @param clients
     */
    @WebMethod(operationName = "CreerClientHLR")
    @RequestWrapper(localName = "CreerClientHLR", targetNamespace = "http://activateSubcriber.tns", className = "tns.activatesubcriber.CreerClientHLR")
    @ResponseWrapper(localName = "CreerClientHLRResponse", targetNamespace = "http://activateSubcriber.tns", className = "tns.activatesubcriber.CreerClientHLRResponse")
    @Action(input = "http://activateSubcriber.tns/WSActivatedSubcriber/CreerClientHLRRequest", output = "http://activateSubcriber.tns/WSActivatedSubcriber/CreerClientHLRResponse")
    public void creerClientHLR(
        @WebParam(name = "Clients", targetNamespace = "")
        Clients clients);

}
