
package tns.activatesubcriber;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WSActivatedSubcriberService", targetNamespace = "http://activateSubcriber.tns", wsdlLocation = "http://localhost:8985/services/WSActivatedSubcriber?wsdl")
public class WSActivatedSubcriberService
    extends Service
{

    private final static URL WSACTIVATEDSUBCRIBERSERVICE_WSDL_LOCATION;
    private final static WebServiceException WSACTIVATEDSUBCRIBERSERVICE_EXCEPTION;
    private final static QName WSACTIVATEDSUBCRIBERSERVICE_QNAME = new QName("http://activateSubcriber.tns", "WSActivatedSubcriberService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8985/services/WSActivatedSubcriber?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSACTIVATEDSUBCRIBERSERVICE_WSDL_LOCATION = url;
        WSACTIVATEDSUBCRIBERSERVICE_EXCEPTION = e;
    }

    public WSActivatedSubcriberService() {
        super(__getWsdlLocation(), WSACTIVATEDSUBCRIBERSERVICE_QNAME);
    }

    public WSActivatedSubcriberService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSACTIVATEDSUBCRIBERSERVICE_QNAME, features);
    }

    public WSActivatedSubcriberService(URL wsdlLocation) {
        super(wsdlLocation, WSACTIVATEDSUBCRIBERSERVICE_QNAME);
    }

    public WSActivatedSubcriberService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSACTIVATEDSUBCRIBERSERVICE_QNAME, features);
    }

    public WSActivatedSubcriberService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSActivatedSubcriberService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSActivatedSubcriber
     */
    @WebEndpoint(name = "WSActivatedSubcriberPort")
    public WSActivatedSubcriber getWSActivatedSubcriberPort() {
        return super.getPort(new QName("http://activateSubcriber.tns", "WSActivatedSubcriberPort"), WSActivatedSubcriber.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSActivatedSubcriber
     */
    @WebEndpoint(name = "WSActivatedSubcriberPort")
    public WSActivatedSubcriber getWSActivatedSubcriberPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://activateSubcriber.tns", "WSActivatedSubcriberPort"), WSActivatedSubcriber.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSACTIVATEDSUBCRIBERSERVICE_EXCEPTION!= null) {
            throw WSACTIVATEDSUBCRIBERSERVICE_EXCEPTION;
        }
        return WSACTIVATEDSUBCRIBERSERVICE_WSDL_LOCATION;
    }

}
