
package tns.createdatasubcriber;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WSCreateNetwork", targetNamespace = "http://createDataSubcriber.tns")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSCreateNetwork {


    /**
     * 
     * @param clients
     */
    @WebMethod
    @RequestWrapper(localName = "creerClientgprs", targetNamespace = "http://createDataSubcriber.tns", className = "tns.createdatasubcriber.CreerClientgprs")
    @ResponseWrapper(localName = "creerClientgprsResponse", targetNamespace = "http://createDataSubcriber.tns", className = "tns.createdatasubcriber.CreerClientgprsResponse")
    @Action(input = "http://createDataSubcriber.tns/WSCreateNetwork/creerClientgprsRequest", output = "http://createDataSubcriber.tns/WSCreateNetwork/creerClientgprsResponse")
    public void creerClientgprs(
        @WebParam(name = "Clients", targetNamespace = "")
        Clients clients);

}
