
package tns.typeoperationsubcriber;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WSTypeOperation", targetNamespace = "http://typeOperationSubcriber.tns")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSTypeOperation {


    /**
     * 
     * @param operation
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "TypeOperation")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "TypeOperation", targetNamespace = "http://typeOperationSubcriber.tns", className = "tns.typeoperationsubcriber.TypeOperation")
    @ResponseWrapper(localName = "TypeOperationResponse", targetNamespace = "http://typeOperationSubcriber.tns", className = "tns.typeoperationsubcriber.TypeOperationResponse")
    @Action(input = "http://typeOperationSubcriber.tns/WSTypeOperation/TypeOperationRequest", output = "http://typeOperationSubcriber.tns/WSTypeOperation/TypeOperationResponse")
    public String typeOperation(
        @WebParam(name = "Operation", targetNamespace = "")
        String operation);

}
