
package tns.typeoperationsubcriber;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WSTypeOperationService", targetNamespace = "http://typeOperationSubcriber.tns", wsdlLocation = "http://localhost:8989/services/WSTypeOperation?wsdl")
public class WSTypeOperationService
    extends Service
{

    private final static URL WSTYPEOPERATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException WSTYPEOPERATIONSERVICE_EXCEPTION;
    private final static QName WSTYPEOPERATIONSERVICE_QNAME = new QName("http://typeOperationSubcriber.tns", "WSTypeOperationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8989/services/WSTypeOperation?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSTYPEOPERATIONSERVICE_WSDL_LOCATION = url;
        WSTYPEOPERATIONSERVICE_EXCEPTION = e;
    }

    public WSTypeOperationService() {
        super(__getWsdlLocation(), WSTYPEOPERATIONSERVICE_QNAME);
    }

    public WSTypeOperationService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSTYPEOPERATIONSERVICE_QNAME, features);
    }

    public WSTypeOperationService(URL wsdlLocation) {
        super(wsdlLocation, WSTYPEOPERATIONSERVICE_QNAME);
    }

    public WSTypeOperationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSTYPEOPERATIONSERVICE_QNAME, features);
    }

    public WSTypeOperationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSTypeOperationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSTypeOperation
     */
    @WebEndpoint(name = "WSTypeOperationPort")
    public WSTypeOperation getWSTypeOperationPort() {
        return super.getPort(new QName("http://typeOperationSubcriber.tns", "WSTypeOperationPort"), WSTypeOperation.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSTypeOperation
     */
    @WebEndpoint(name = "WSTypeOperationPort")
    public WSTypeOperation getWSTypeOperationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://typeOperationSubcriber.tns", "WSTypeOperationPort"), WSTypeOperation.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSTYPEOPERATIONSERVICE_EXCEPTION!= null) {
            throw WSTYPEOPERATIONSERVICE_EXCEPTION;
        }
        return WSTYPEOPERATIONSERVICE_WSDL_LOCATION;
    }

}
