
package tns.authentification;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WSAuthentification", targetNamespace = "http://authentification.tns")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSAuthentification {


    /**
     * 
     * @param password
     * @param login
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "authentification", targetNamespace = "http://authentification.tns", className = "tns.authentification.Authentification")
    @ResponseWrapper(localName = "authentificationResponse", targetNamespace = "http://authentification.tns", className = "tns.authentification.AuthentificationResponse")
    @Action(input = "http://authentification.tns/WSAuthentification/authentificationRequest", output = "http://authentification.tns/WSAuthentification/authentificationResponse")
    public boolean authentification(
        @WebParam(name = "login", targetNamespace = "")
        String login,
        @WebParam(name = "password", targetNamespace = "")
        String password);

}
