
package tns.desactivesubcriber;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WSDesactivateSubcriberService", targetNamespace = "http://desactiveSubcriber.tns", wsdlLocation = "http://localhost:8983/services/WSDesactivateSubcriber?wsdl")
public class WSDesactivateSubcriberService
    extends Service
{

    private final static URL WSDESACTIVATESUBCRIBERSERVICE_WSDL_LOCATION;
    private final static WebServiceException WSDESACTIVATESUBCRIBERSERVICE_EXCEPTION;
    private final static QName WSDESACTIVATESUBCRIBERSERVICE_QNAME = new QName("http://desactiveSubcriber.tns", "WSDesactivateSubcriberService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8983/services/WSDesactivateSubcriber?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSDESACTIVATESUBCRIBERSERVICE_WSDL_LOCATION = url;
        WSDESACTIVATESUBCRIBERSERVICE_EXCEPTION = e;
    }

    public WSDesactivateSubcriberService() {
        super(__getWsdlLocation(), WSDESACTIVATESUBCRIBERSERVICE_QNAME);
    }

    public WSDesactivateSubcriberService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSDESACTIVATESUBCRIBERSERVICE_QNAME, features);
    }

    public WSDesactivateSubcriberService(URL wsdlLocation) {
        super(wsdlLocation, WSDESACTIVATESUBCRIBERSERVICE_QNAME);
    }

    public WSDesactivateSubcriberService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSDESACTIVATESUBCRIBERSERVICE_QNAME, features);
    }

    public WSDesactivateSubcriberService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSDesactivateSubcriberService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSDesactivateSubcriber
     */
    @WebEndpoint(name = "WSDesactivateSubcriberPort")
    public WSDesactivateSubcriber getWSDesactivateSubcriberPort() {
        return super.getPort(new QName("http://desactiveSubcriber.tns", "WSDesactivateSubcriberPort"), WSDesactivateSubcriber.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSDesactivateSubcriber
     */
    @WebEndpoint(name = "WSDesactivateSubcriberPort")
    public WSDesactivateSubcriber getWSDesactivateSubcriberPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://desactiveSubcriber.tns", "WSDesactivateSubcriberPort"), WSDesactivateSubcriber.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSDESACTIVATESUBCRIBERSERVICE_EXCEPTION!= null) {
            throw WSDESACTIVATESUBCRIBERSERVICE_EXCEPTION;
        }
        return WSDESACTIVATESUBCRIBERSERVICE_WSDL_LOCATION;
    }

}
