
package tns.desactivesubcriber;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WSDesactivateSubcriber", targetNamespace = "http://desactiveSubcriber.tns")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSDesactivateSubcriber {


    /**
     * 
     * @param numero
     */
    @WebMethod(operationName = "SupprimerClientHlr")
    @RequestWrapper(localName = "SupprimerClientHlr", targetNamespace = "http://desactiveSubcriber.tns", className = "tns.desactivesubcriber.SupprimerClientHlr")
    @ResponseWrapper(localName = "SupprimerClientHlrResponse", targetNamespace = "http://desactiveSubcriber.tns", className = "tns.desactivesubcriber.SupprimerClientHlrResponse")
    @Action(input = "http://desactiveSubcriber.tns/WSDesactivateSubcriber/SupprimerClientHlrRequest", output = "http://desactiveSubcriber.tns/WSDesactivateSubcriber/SupprimerClientHlrResponse")
    public void supprimerClientHlr(
        @WebParam(name = "numero", targetNamespace = "")
        String numero);

}
