
package tns.createinsubcriber;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WSINConnectionService", targetNamespace = "http://createINSubcriber.tns", wsdlLocation = "http://localhost:8285/services/WSINConnection?wsdl")
public class WSINConnectionService
    extends Service
{

    private final static URL WSINCONNECTIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException WSINCONNECTIONSERVICE_EXCEPTION;
    private final static QName WSINCONNECTIONSERVICE_QNAME = new QName("http://createINSubcriber.tns", "WSINConnectionService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8285/services/WSINConnection?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSINCONNECTIONSERVICE_WSDL_LOCATION = url;
        WSINCONNECTIONSERVICE_EXCEPTION = e;
    }

    public WSINConnectionService() {
        super(__getWsdlLocation(), WSINCONNECTIONSERVICE_QNAME);
    }

    public WSINConnectionService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSINCONNECTIONSERVICE_QNAME, features);
    }

    public WSINConnectionService(URL wsdlLocation) {
        super(wsdlLocation, WSINCONNECTIONSERVICE_QNAME);
    }

    public WSINConnectionService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSINCONNECTIONSERVICE_QNAME, features);
    }

    public WSINConnectionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSINConnectionService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSINConnection
     */
    @WebEndpoint(name = "WSINConnectionPort")
    public WSINConnection getWSINConnectionPort() {
        return super.getPort(new QName("http://createINSubcriber.tns", "WSINConnectionPort"), WSINConnection.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSINConnection
     */
    @WebEndpoint(name = "WSINConnectionPort")
    public WSINConnection getWSINConnectionPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://createINSubcriber.tns", "WSINConnectionPort"), WSINConnection.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSINCONNECTIONSERVICE_EXCEPTION!= null) {
            throw WSINCONNECTIONSERVICE_EXCEPTION;
        }
        return WSINCONNECTIONSERVICE_WSDL_LOCATION;
    }

}
