
package tns.createinsubcriber;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WSINConnection", targetNamespace = "http://createINSubcriber.tns")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSINConnection {


    /**
     * 
     * @param clients
     */
    @WebMethod
    @RequestWrapper(localName = "creerClientIN", targetNamespace = "http://createINSubcriber.tns", className = "tns.createinsubcriber.CreerClientIN")
    @ResponseWrapper(localName = "creerClientINResponse", targetNamespace = "http://createINSubcriber.tns", className = "tns.createinsubcriber.CreerClientINResponse")
    @Action(input = "http://createINSubcriber.tns/WSINConnection/creerClientINRequest", output = "http://createINSubcriber.tns/WSINConnection/creerClientINResponse")
    public void creerClientIN(
        @WebParam(name = "Clients", targetNamespace = "")
        Clients clients);

}
