
package tns.deleteinsubcriber;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WSTermination", targetNamespace = "http://deleteInSubcriber.tns")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSTermination {


    /**
     * 
     * @param numero
     */
    @WebMethod(operationName = "SupprimerClientIn")
    @RequestWrapper(localName = "SupprimerClientIn", targetNamespace = "http://deleteInSubcriber.tns", className = "tns.deleteinsubcriber.SupprimerClientIn")
    @ResponseWrapper(localName = "SupprimerClientInResponse", targetNamespace = "http://deleteInSubcriber.tns", className = "tns.deleteinsubcriber.SupprimerClientInResponse")
    @Action(input = "http://deleteInSubcriber.tns/WSTermination/SupprimerClientInRequest", output = "http://deleteInSubcriber.tns/WSTermination/SupprimerClientInResponse")
    public void supprimerClientIn(
        @WebParam(name = "numero", targetNamespace = "")
        String numero);

}
