
package tns.deletedatasubcriber;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WSDeleteNetworkService", targetNamespace = "http://DeleteDataSubcriber.tns", wsdlLocation = "http://localhost:8281/services/WSDeleteNetwork?wsdl")
public class WSDeleteNetworkService
    extends Service
{

    private final static URL WSDELETENETWORKSERVICE_WSDL_LOCATION;
    private final static WebServiceException WSDELETENETWORKSERVICE_EXCEPTION;
    private final static QName WSDELETENETWORKSERVICE_QNAME = new QName("http://DeleteDataSubcriber.tns", "WSDeleteNetworkService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8281/services/WSDeleteNetwork?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSDELETENETWORKSERVICE_WSDL_LOCATION = url;
        WSDELETENETWORKSERVICE_EXCEPTION = e;
    }

    public WSDeleteNetworkService() {
        super(__getWsdlLocation(), WSDELETENETWORKSERVICE_QNAME);
    }

    public WSDeleteNetworkService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSDELETENETWORKSERVICE_QNAME, features);
    }

    public WSDeleteNetworkService(URL wsdlLocation) {
        super(wsdlLocation, WSDELETENETWORKSERVICE_QNAME);
    }

    public WSDeleteNetworkService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSDELETENETWORKSERVICE_QNAME, features);
    }

    public WSDeleteNetworkService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSDeleteNetworkService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSDeleteNetwork
     */
    @WebEndpoint(name = "WSDeleteNetworkPort")
    public WSDeleteNetwork getWSDeleteNetworkPort() {
        return super.getPort(new QName("http://DeleteDataSubcriber.tns", "WSDeleteNetworkPort"), WSDeleteNetwork.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSDeleteNetwork
     */
    @WebEndpoint(name = "WSDeleteNetworkPort")
    public WSDeleteNetwork getWSDeleteNetworkPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://DeleteDataSubcriber.tns", "WSDeleteNetworkPort"), WSDeleteNetwork.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSDELETENETWORKSERVICE_EXCEPTION!= null) {
            throw WSDELETENETWORKSERVICE_EXCEPTION;
        }
        return WSDELETENETWORKSERVICE_WSDL_LOCATION;
    }

}
