
package tns.deletedatasubcriber;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WSDeleteNetwork", targetNamespace = "http://DeleteDataSubcriber.tns")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSDeleteNetwork {


    /**
     * 
     * @param numero
     */
    @WebMethod(operationName = "SupprimerClientGprs")
    @RequestWrapper(localName = "SupprimerClientGprs", targetNamespace = "http://DeleteDataSubcriber.tns", className = "tns.deletedatasubcriber.SupprimerClientGprs")
    @ResponseWrapper(localName = "SupprimerClientGprsResponse", targetNamespace = "http://DeleteDataSubcriber.tns", className = "tns.deletedatasubcriber.SupprimerClientGprsResponse")
    @Action(input = "http://DeleteDataSubcriber.tns/WSDeleteNetwork/SupprimerClientGprsRequest", output = "http://DeleteDataSubcriber.tns/WSDeleteNetwork/SupprimerClientGprsResponse")
    public void supprimerClientGprs(
        @WebParam(name = "numero", targetNamespace = "")
        String numero);

}
